# user-designated list of strains/species; add your sample names below, without ".fasta" extension
samples:
  - <sample 1>
  - <sample 2>
  - ...

# user-provided, two-column ("strain"; "species") list of strains for FastANI input; add the sample names as designated above
# if 1 or more input strains are reference genomes, or otherwise have known species designations, add species names to "species" column; otherwise, leave "species" blank.
strains_meta: "FastANI/strains.txt"

# user-provided outgroup strain; add a strain ID from the list above
# user-provided housekeeping (HK) gene FASTA for MLSA
automlsa2_outgroup: "<outgroup species/strain>"
automlsa2_query: "automlsa2/HK_genes.fasta"

# directories for tblastn
blast_dir: BLAST
fasta_dir: FASTA
blast_db_dir: BLAST/database

# user-provided gene query FAAs (amino acid FASTA files) for tblastn
blast_queries:
  <gene 1>: BLAST/<gene 1>.faa
  <gene 2>: BLAST/<gene 2>.faa
  ...

# user-provided inputs for gene presence/absence analysis
# ensure that "gene_files" (from BLAST.smk) & "query_lengths" (lengths, in amino acids, for each gene of interest) match "blast_queries" above
# "_thresh" values can be adjusted per user preference
gene_files:
  <gene 1>: "BLAST/<gene 1>_combined.txt"
  <gene 1>: "BLAST/<gene 2>_combined.txt"
  ...

query_lengths:
  <gene 1>: <length, aa>
  <gene 2>: <length, aa>
  ...

identity_thresh: 70.0
coverage_thresh: 70.0
evalue_thresh: 1e-5


  


